### ISSUE TITLE
Nodebb compatibility

### ISSUE THREAD

**Issue by ic3fresh** [NicolasSiver/nodebb-plugin-ns-spoiler#15]
Hey, it seems that plugin is not compatible with newest nodebb. I'm not sure if this can be fixed quickly though.

**Comment by fais3000** [comment]
Yes, same here. Testing on v1.11.1. It crashes at 

`2019-01-08T03:08:25.894Z [4567/18244] - [31merror[39m: Error: Cannot find module './src/emitter'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Module.require.main.require (/var/www/nodebb/require-main.js:8:10)
    at /var/www/nodebb/node_modules/nodebb-plugin-ns-spoiler/plugin/nodebb.js:10:31
    at Object.<anonymous> (/var/www/nodebb/node_modules/nodebb-plugin-ns-spoiler/plugin/nodebb.js:47:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at /var/www/nodebb/node_modules/nodebb-plugin-ns-spoiler/plugin/controller.js:7:21
    at Object.<anonymous> (/var/www/nodebb/node_modules/nodebb-plugin-ns-spoiler/plugin/controller.js:63:3)`

**Comment by NicolasSiver** [comment]
v6 should work with 1.11.x NodeBB.
