### ISSUE TITLE
Images dont show up

### ISSUE THREAD

**Issue by Master-GitHub** [NicolasSiver/nodebb-plugin-ns-spoiler#13]
Hi!

Images in spoiler dont show up. I would be grateful for help.

Nodebb version: v1.8.2

Link to Nodebb community topic: https://community.nodebb.org/topic/12246/fix-spoiler-plugin

Error in console:
```
spoiler.js:57 Uncaught TypeError: e.unloadImages is not a function
    at i.<anonymous> (spoiler.js:57)
    at i.onack (socket.io.js:2)
    at i.onpacket (socket.io.js:2)
    at i.<anonymous> (socket.io.js:2)
    at i.emit (socket.io.js:1)
    at i.ondecoded (socket.io.js:1)
    at a.<anonymous> (socket.io.js:2)
    at a.i.emit (socket.io.js:1)
    at a.add (socket.io.js:1)
    at i.ondata (socket.io.js:1)
```

**Comment by NicolasSiver** [comment]
Hello,

The plugin was designed to work with NodeBB v1.1.0. And any minor version after that.
There was a breaking change in the minor release.

I will look into it this week.

**Comment by Master-GitHub** [comment]
Thanks :D

**Comment by metahusk** [comment]
Does the fix work on v1.9.x? Thanks for your effort.

**Comment by NicolasSiver** [comment]
Every minor version increase in NodeBB could be breaking.
Would be great, if you will try and tell us if it's working. The latest version of Spoiler Plugin is for `1.8`.

**Comment by metahusk** [comment]
I'll try and test it soon and get back to you.

**Comment by Master-GitHub** [comment]
Working on 1.9.0.

**Comment by metahusk** [comment]
It worked for me in 1.9.0 with a single spoiler in a post. 

When I try to combine multiple spoilers with text and markup, sometimes images disappear. I spent a few hours trying to identify what in my post causes the issues, instead I just made separate posts for each spoiler. I think maybe it has something to do with running nodebb-plugin-markdown as well. I didn't see it as that big of an issue. Also, I was using Opera at the time. I didn't try other browsers.

I'm just reporting back my findings. I don't think it justifies any time on your end if you've got a lot of other projects going on. Thanks for getting the plugin working.

**Comment by NicolasSiver** [comment]
Could you share the post markup which breaks for you?

**Comment by metahusk** [comment]
### About:
Here is the game menu from our game, Cardinal Fall, for use by the community.
This project packages a combination of other community projects to create a single, easy to implement menu system. 
We will do our best to update the project with new engine releases.

### License:
This Menu System is free to use under the Creative Commons Attribution 4.0 International License. CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/) 
3rd Party Assets are discussed in the credits section below. 
More up to date information is available in the Readme.

### Screenshots:
(To view screenshots, click the button below.)
 
:::
 
![0_1470957328119_FriendsList.PNG](https://i.imgur.com/1pPHKWs.png) 
![0_1470957340083_HostGame.PNG](https://i.imgur.com/DScaAS7.png) 
![0_1470957382025_ServerList.PNG](https://i.imgur.com/0N3B3NV.png) 
 
:::
 
### Video:
https://youtu.be/vpIki4P95WM

### Features:
* Server Browser (With Steam and LAN support)
* Client Internet and LAN Hosting Menu
* Steam Friends List With Avatars
* Pervasive Graphics Settings
* Player Control Mapping
* Controller Support
* Game Settings
* Credits Page

### Download:

[Metahusk Downloads: Cardinal Menu](http://metahusk.com/cardinal-menu/) 

### Getting Started:
(To read the directions, click the button below.)
 
:::
 
1. Create a Project Directory folder in your Unreal 4 Projects Directory.
> **Example Structure:** C:\Users\User\Documents\Unreal Projects\Directory_Name

2. Download the project or Clone the development files to your Unreal 4 Projects Directory using your favorite mercurial client.
>  **Hg Repository URL:** http://repositories.metahusk.com/menu.hg

 > **Common Mercurial Clients:** [SourceTree](http://www.sourcetreeapp.com/), [TortoiseHG](http://tortoisehg.bitbucket.org/), or [SmartGitHG](http://www.syntevo.com/smartgit/)

3. Download and Install Microsoft's Visual Studio Community 2015 for Windows Desktop
>  [Visual Studio Community 2015](https://www.visualstudio.com)

4a. Navigate to \Your_Directory\Plugins and extract the files in VictoryPlugin(newest-version).zip to the plugins directory into a folder called VictoryPlugin
>  **Plugins Directory Structure:** \Your_Directory\Plugins\VictoryPlugin\"plugin files"

4b. *ONLY UE4.14 and PREVIOUS:* Navigate to \Your_Directory\Plugins and extract the files in MainMenuLib(newest-version).zip to the plugins directory into a folder called MainMenuLib
>  **Plugins Directory Structure:** \Your_Directory\Plugins\MainMenuLib\"plugin files"

4c. Navigate to \Your_Directory\Plugins and extract the files in AdvancedSessions(newest-version).zip to the plugins directory into a folder called AdvancedSessions
>  **Plugins Directory Structure:** \Your_Directory\Plugins\AdvancedSessions\"plugin files"

4d. Navigate to \Your_Directory\Plugins and extract the files in LoadingScreen-master(newest-version).zip to the plugins directory into a folder called LoadingScreen-master
>  **Plugins Directory Structure:** \Your_Directory\Plugins\LoadingScreen-master\"plugin files"

4e. Navigate to \Your_Directory\Plugins and extract the files in GamepadUMGPlugin(newest-version).zip to the plugins directory into a folder called GamepadUMGPlugin
>  **Plugins Directory Structure:** \Your_Directory\Plugins\GamepadUMGPlugin\"plugin files"

4f. Navigate to \Your_Directory\Plugins and extract the files in PingPlugin(newest-version).zip to the plugins directory into a folder called PingPlugin
>  **Plugins Directory Structure:** \Your_Directory\Plugins\PingPlugin\"plugin files"

4g. Navigate to \Your_Directory\Plugins and extract the files in VaRest(newest-version).zip to the plugins directory into a folder called VaRest
>  **Plugins Directory Structure:** \Your_Directory\Plugins\VaRest\"plugin files"

5. Right Click on cardinal.uproject and click Generate Visual Studio project files.

6. Execute cardinal.uproject and click _Yes_ to Recompile Project Modules.
![0_1470810235398_rebuild.PNG](https://i.imgur.com/urn3OtI.png) 

7. Enable The Web Browser Plugin at Edit -> Plugins -> Widgets -> Web Browser
![0_1470814419201_browser.PNG](https://i.imgur.com/UMlwnYr.png) 

8. Enjoy :) 
***NOTE: To utilize Steam, you must launch as a "Standalone Game" or utilize a packaged build both with Steam running.***
![0_1470810240172_play.PNG](https://i.imgur.com/QXPB6HY.png)
 
:::
 
### How To Import Cardinal Menu To Your Project:
(To read the directions, click the button below.)
 
:::
 
1. Open your project's Project Directory folder in windows explorer.
> **Example Structure:** C:\Users\User\Documents\Unreal Projects\Project_Name

2. Download the project files from the webpage.
>  **Download URL:** metahusk.com/cardinal-menu/

3. Convert your project to a C++ project if it's a Blueprint Only project.
>  [Convert a BP/Content Project to a C++ Project](https://wiki.unrealengine.com/How_to_Convert_a_BP/Content_Project_to_a_C%2B%2B_Project_in_8_Steps)

4. Navigate to \Your_Directory\Content and extract the \CardinalMenu\Content\Cardinal and \CardinalMenu\Content\ThirdPersonExample and \CardinalMenu\Content\Movies into your project's content folder.

5. Navigate to \Your_Directory and extract the \CardinalMenu\Plugins folder into your project's root directory.

6a. Navigate to \Your_Directory\Plugins and extract the files in VictoryPlugin(newest-version).zip to the plugins directory into a folder called VictoryPlugin
>  **Plugins Directory Structure:** \Your_Directory\Plugins\VictoryPlugin\"plugin files"

6b. *ONLY UE4.14 and PREVIOUS:* Navigate to \Your_Directory\Plugins and extract the files in MainMenuLib(newest-version).zip to the plugins directory into a folder called MainMenuLib
>  **Plugins Directory Structure:** \Your_Directory\Plugins\MainMenuLib\"plugin files"

6c. Navigate to \Your_Directory\Plugins and extract the files in AdvancedSessions(newest-version).zip to the plugins directory into a folder called AdvancedSessions
>  **Plugins Directory Structure:** \Your_Directory\Plugins\AdvancedSessions\"plugin files"

6d. Navigate to \Your_Directory\Plugins and extract the files in LoadingScreen-master(newest-version).zip to the plugins directory into a folder called LoadingScreen-master
>  **Plugins Directory Structure:** \Your_Directory\Plugins\LoadingScreen-master\"plugin files"

6e. Navigate to \Your_Directory\Plugins and extract the files in GamepadUMGPlugin(newest-version).zip to the plugins directory into a folder called GamepadUMGPlugin
>  **Plugins Directory Structure:** \Your_Directory\Plugins\GamepadUMGPlugin\"plugin files"

6f. Navigate to \Your_Directory\Plugins and extract the files in PingPlugin(newest-version).zip to the plugins directory into a folder called PingPlugin
>  **Plugins Directory Structure:** \Your_Directory\Plugins\PingPlugin\"plugin files"

6g. Navigate to \Your_Directory\Plugins and extract the files in VaRest(newest-version).zip to the plugins directory into a folder called VaRest
>  **Plugins Directory Structure:** \Your_Directory\Plugins\VaRest\"plugin files"

7. Open \CardinalMenu\Source\CardinalMenu.Target.cs and paste bUsesSteam = true; into your  \Your_Directory\Source\YourProject.Target.cs like so:
>public class YourProjectTarget : TargetRules
>{
>	public YourProjectTarget(TargetInfo Target)
>	{
>		Type = TargetType.Game;
>       bUsesSteam = true;
>    }

8. Open \CardinalMenu\Source\CardinalMenu\CardinalMenu.Build.cs and paste the PublicDependencyModuleNames and PrivateDependencyModuleNames into your  \Your_Directory\Source\YourProject\YourProject.Build.cs like so:

>      PublicDependencyModuleNames.AddRange(new string[] { "Core", "CoreUObject", "Engine", "InputCore",  "AdvancedSessions", "OnlineSubsystem", "OnlineSubsystemUtils", "Networking", "Sockets", "OnlineSubsystemSteam", "OnlineSubsystemNull", "MoviePlayer" });

*NOTE:* If UE4.14 or previous, add "MainMenuLib" to PublicDependencyModuleNames

 >       PrivateDependencyModuleNames.AddRange(new string[] { "OnlineSubsystem", "Sockets", "Networking", "OnlineSubsystemSteam", "OnlineSubsystemNull" });

9. Open \CardinalMenu\Config\DefaultEngine.ini and paste the following into your  \Your_Directory\Config\DefaultEngine.ini as shown:


>[/Script/Engine.GameEngine]
>!NetDriverDefinitions=ClearArray
>+NetDriverDefinitions=>(DefName="GameNetDriver",DriverClassName="/Script/OnlineSubsystemSteam.SteamNetDriver",DriverClassNameFallback="/Script/OnlineSubsystemUtils.IpNetDriver")
 
>[OnlineSubsystem]
>DefaultPlatformService=Steam
>PollingIntervalInMs=20
>bHasVoiceEnabled=false
 
>[OnlineSubsystemSteam]
>bEnabled=true
>SteamDevAppId=480
>GameServerQueryPort=27015
>bRelaunchInSteam=false
>GameVersion=1.0.0.0
>bVACEnabled=1
>bAllowP2PPacketRelay=true
>P2PConnectionTimeout=90
 
>[/Script/OnlineSubsystemSteam.SteamNetDriver]
>NetConnectionClassName="/Script/OnlineSubsystemSteam.SteamNetConnection"

>[Voice] 
>bEnabled=false

10. Right click on \Your_Directory\YourProject.uproject  and select Generate Visual Studio project files.

11. Open YourProject.sln, in Solution Explorer (typically located on the right) right click on Games and select Build.

12. Execute cardinal.uproject and click _Yes_ to Recompile Project Modules, if asked.
![0_1470810235398_rebuild.PNG](https://i.imgur.com/urn3OtI.png) 

13. Open Project Settings and select Maps and Modes. Set Game Default Map and Editor Startup Map to MainMenu. Set Default GameMode to ThirdPersonGameMode. Set the Game Instance Class to BP_GameInstance.

14. Open the map MainMenu File -> Open Level at /Cardina/Mainmenu/Maps. Under the Blueprints button above the map make sure World Override is set to  -> BP_MenuGameMode (should be set)

15a. Enable The Web Browser Plugin at Edit -> Plugins -> Widgets -> Web Browser
![0_1470814419201_browser.PNG](https://i.imgur.com/UMlwnYr.png) 

15b. *UE4.14 or Previous Only* Enable MainMenuLib Plugin at Edit -> Plugins -> Other -> MainMenuLib

15c. Enable Loading Screen Plugin at Edit -> Plugins -> Loading -> Loading Screen

15d. Enable Advanced Sessions Plugin at Edit -> Plugins -> Advanced Sessions Plugin -> Advanced Sessions

15e. Enable Online Subsystem Steam Plugin at Edit -> Plugins -> Online Platform -> Online Subsystem Steam

15f. Enable Gamepad UMG Plugin and Victory Plugin at Edit -> Plugins -> Installed -> Rama

15g. Enable PingPlugin and Victory Plugin at Edit -> Plugins -> Network -> Ping

15h. Enable VaRest Plugin and Victory Plugin at Edit -> Plugins -> Network -> VaRest

16. Restart The Editor and click _Yes_ to Recompile Project Modules, if asked.

17. Set Up LoadingScreen by opening Edit -> Project Settings -> Game -> Loading Screen. Under Startup Screen Uncheck Auto Complete when Loading Completes, Check Movies are Skippable, Uncheck Wait For Manual Stop,  Uncheck Show UIOverlay. Go to Movie Paths and add UE4Logo and MetahuskIntro to the array. Under Default Screen Check Auto Complete when Loading Completes, Check Movies are Skippable, Uncheck Wait For Manual Stop,  Uncheck Show UIOverlay. Go to Movie Paths and add LoadingRed to the array.

18. Navigate to the MainMenu Blueprints folder at \Cardinal\MainMenu\Blueprints
![0_1470810249459_enumerations.PNG](https://i.imgur.com/hZGUni9.png) 

19. Insert your GameModes into Enum_GameModes, list your available map names to Enum_Maps, and set your server host's preferred maximum number of players to Enum_NumberOfPlayers using the supplied pattern. For skipped number of player options, use the enumeration's integer. For the number of players option you'd like available, spell out the integer. For example: 0, 1, Three will leave a server with a maximum of "Three Players." (Please note the game modes and player limits are not implemented in the actual project. This is up to the end user to implement.)
![0_1470810298370_gamemodes.PNG](https://i.imgur.com/mmk3Hju.png) 
![0_1470810343718_maps.PNG](https://i.imgur.com/Y2izqfV.png) 
![0_1470810359503_players.PNG](https://i.imgur.com/wNS4NEJ.png) 

20. Enjoy :) 
***NOTE: To utilize Steam, you must launch as a "Standalone Game" or utilize a packaged build both with Steam running.***
![0_1470810240172_play.PNG](https://i.imgur.com/QXPB6HY.png)
 
:::
 

### Modifying Starting Map or Number of Players

1. Navigate to the MainMenu Blueprints folder at \Cardinal\MainMenu\Blueprints
2. Insert your GameModes into Enum_GameModes, list your available map names to Enum_Maps, and set your server host's preferred maximum number of players to Enum_NumberOfPlayers using the supplied pattern. 
For skipped number of player options, use the enumeration's integer. For the number of players option you'd like available, spell out the integer. 
For example: 0, 1, Three will make a server with a maximum of "Three Players." (Please note the game modes and player limits are not implemented in the actual project. This is up to the end user to implement.)


### Deploying Packaged Builds

In order for key bindings to work on packaged builds, you must copy Input.ini from inside your project to the build directory.
The paths and default bindings are listed below. Input.ini does not copy into the directory by itself. The default bindings are shown below for your convenience.

### Windows US Keyboard Default Input Bindings
Inside Project Directories:
\Saved\Config\Windows\Input.ini and Saved\Config\WindowsNoEditor\Input.ini and \Config\DefaultInput.ini
Inside Packaged Game Directory:
\WindowsNoEditor\CardinalMenu\Saved\Config\WindowsNoEditor\Input.ini 

Input.ini Default Windows Bindings:
[/Script/Engine.InputSettings]
ActionMappings=(ActionName="Jump",Key=SpaceBar,bShift=False,bCtrl=False,bAlt=False,bCmd=False)
ActionMappings=(ActionName="Menu",Key=M,bShift=False,bCtrl=False,bAlt=False,bCmd=False)
AxisMappings=(AxisName="Backward",Key=S,Scale=-1.000000)
AxisMappings=(AxisName="Forward",Key=W,Scale=1.000000)
AxisMappings=(AxisName="LookDown",Key=None,Scale=1.000000)
AxisMappings=(AxisName="LookUp",Key=MouseY,Scale=-1.000000)
AxisMappings=(AxisName="TurnLeft",Key=MouseX,Scale=1.000000)
AxisMappings=(AxisName="TurnRight",Key=None,Scale=-1.000000)

[/Script/Engine.Console]
HistoryBuffer=mexit
HistoryBuffer=exit

### Known Bugs:
(To view the known bugs, click the button below.)
 
:::
 
**Bug:** Client Returning to "Main Menu" can't join another game.
**Fix:** Fixed 08/07/2016 at Changeset - a1943cb579fc

**Bug:** The Editor's Play In Viewport option does not stretch the menu title bar all the way to the edge of the screen on some resolutions
**Fix:** Use Play In New Editor Window

**Bug:** Split screen menu cannot be scaled to overlay on the calling player's screen
**Fix:** Unknown, possibly in future engine release

**Bug:** Player input control mappings are not in the correct order
**Fix:** The engine re-orders inputs, change them to alphabetical order in your DefaultInput.ini

**Bug:** Packaged game builds lose default control bindings
**Fix:** Packaging does not copy Input.ini by itself. See "Deploying Packaged Builds" above

**Bug:** Cannot host a session after importing project files
**Fix:** Make sure BP_GameInstance is set in your game mode

**Bug:** Joining players in PIE spawn as spectators and not pawns
**Fix:** Make sure Auto Connect To Servers is not checked under Play -> Advanced Settings -> Multiplayer options

**Bug:** Some listen servers do not respond to ping, instead respond with "?"
**Fix:** Listen server host's network configuration (firewall or router) do not respond to ICMP Pings, likely do to configuration.
 
:::
 
### Credits:

 **Project Credits:** 
Metahusk, mordentral, rama, Thaddeus Delude (parvan), The Tune Peddler, ZioYuri78, Nick Darnell

**Cardinal Menu:**
This project was put together by Metahusk using a collection of community content. Please credit everyone listed here and provide a link to our websites.
(http://metahusk.com)

**Project Blueprints:**
This project’s blueprint files are released under the Creative Commons Attribution 4.0 International License. CC BY 4.0
Please provide credit where credit is due. You must credit the following people listed below. You can find this information in the project’s readme.
(https://creativecommons.org/licenses/by/4.0/) 

**Main Menu by ZioYuri78:**
The basic menu framework is an adaptation of ZioYuri78’s ‘Main menu and in game menu with basic game, graphics, controls and audio settings.’
(https://forums.unrealengine.com/showthread.php?103583-C-Blueprint-Main-menu-and-in-game-menu-with-basic-game-graphics-controls-and-audio-settings)

**Online Browser by mordentral:**
The online browser utilizes mordentral’s Advanced Sessions Plugin.
(https://forums.unrealengine.com/showthread.php?69901-Advanced-Sessions-Plugin)

**Rebindable Keys by rama:**
The key binding system utilizes Rama’s UMG Rebindable Key System, Rebind keys at Runtime.
(https://forums.unrealengine.com/showthread.php?51449-Full-Project-Rama-s-UMG-Rebindable-Key-System-Rebind-keys-at-Runtime!)

**Background Music by The Tune Peddler:**
The music used in this project is owned by The Tune Peddler. You do not have permission to use the project’s music without agreeing to the terms at The Tune Peddler’s website. As of July 2016, this includes a $5 a month subscription fee.
(http://thetunepeddler.com/)

**LoadingScreen plugin by Nick Darnell:**
The LoadingScreen plugin was provided by Nick Darnell and was released under The MIT License. 
(https://github.com/ue4plugins/LoadingScreen)

### How To Help:

Respond to this thread below with your ideas. 
If you have a bug fix, would like to contribute,  or expand on this project, please say so. 
We will contact you and grant you commit privileges on the repository.

### How To Donate:

Our organization is a IRS 501(c)(3) recognized tax exempt nonprofit.
We will provide written (emailed) donor acknowledgment letters to those who donate $250 or more to our organization as required by the IRS. Our apologies to donors outside of the United States. We will not be able to provide you with any tax benefits for donating to our organization.

#### Donation acknowledgment letters will include
> The corporate name and EIN of our organization
> The name of the donor as it appears on PayPal
> The date and ammount of the contribution
> A statement that our organization is a valid 501(c)(3) organization
> An affirmation that no goods or services were provided to the donor
> And information about how your donation was used

Thank you,
[Donate Through Paypal Here](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MSXKLJFLLEVR6)

**Comment by NicolasSiver** [comment]
@metahusk there is an issue with the provided markup. Will look into it for the possible solution.

One more recommendation for the provided markdown. Blockquotes do not work well with lists. Formatting for the list is pretty complex. Consider using paragraphs, i.e.

```
**Step 1**

Some explanation for the step. But now you can do any complex layout.

**Step 2**

An explanation for the step 2, and so on.

// VS

1. Complex Layout.
2. Complex Layout.
```

**Comment by metahusk** [comment]
@NicolasSiver I was wondering if it had something to do with complex markup and lists. Thanks for your help.

**Comment by r0v** [comment]
I have the same problem, NodeBB version 1.9.3 and `t.unloadImages is not a function` coma back.

**Comment by Brophy** [comment]
Images don't work for me in spoiler tags on 1.9.3
